### ISSUE TITLE
Quickstart (US Landfire) wiki needs clarification

### ISSUE THREAD

**Issue by mcgratta** [firetools/qgis2fds#11]
I created a new fds input file using QGIS2FDS, but the resulting geometry was rotated compared to the FDS domain. I guess that I've made some mistake with the coordinate system. So I decided to set up a new QGIS project and go through the process again. The section of the wiki entitled "Open a new project" is not clear. It is not clear to me how to select the CRS for the project. I choose WGS84 from two lists, and then I cannot manage to get Source CRS Destination. I think the problem is that the Windows and Mac versions of the software might be a bit different. When I click the + sign, a new dialog opens, but I cannot find the filter button, etc. 

I suggest that someone go through these notes using a Windows computer and make sure things are the same. My menus are not exactly like the windows shown in the notes. Like I cannot highlight WGS84 on the Predefined and Recently used lists at the same time. I don't know how to actually select this as the default. 

Also, what is confusing about the notes is that the reader is often told to do something, but then told how to do it later. I struggle to figure out how to do something, only to read on and see it explained. For example:

"After opening a new empty project, set its CRS (Coordinate Reference System) to WGS84 - EPSG:4326 for simplicity. Click on the Project > Properties menu, and select the CRS panel."

The first sentence tells me to do something, but the second sentence tells me how. I would word it this way:

"After opening a new empty project, set its CRS (...) by clicking on Project > Properties and selecting the CRS panel...."

Now explain how to select WGS, etc.  This seems like a minor detail, but as I read the notes, I was never sure whether I had already done a particular task.

**Comment by emanuelegissi** [comment]
Ok, this is the kind of feedback that we need!
I am going to fix it.
Emanuele

**Comment by emanuelegissi** [comment]
After a substantial rewrite, I just uploaded an attempt to fix this issue. Please, take a look at the LANDFIRE wiki page and tell me if it is clear enough.
I am leaving this issue open until you tell me it is ok.

**Comment by emanuelegissi** [comment]
Okay
