### ISSUE TITLE
Viewing of OpenStreetMaps

### ISSUE THREAD

**Issue by mcgratta** [firetools/qgis2fds#12]
I must have done something wrong, but I can no longer view the OpenStreetMaps. I don't know what CRS it should have. At some point, the map of Africa was superimposed on top of the US. Can you provide clarification as to how to view the street maps on top of the elevation and landuse data. Whatever defaults existed are no longer, and I even uninstalled and reinstalled, but these various settings remain.

**Comment by emanuelegissi** [comment]
Tomorrow my wife is on a day shift so I am available for a video call, if
you want.

**Comment by mcgratta** [comment]
It would be better if you add a few details to the wiki, and then I can try to see if it works. If you just tell me what to do, then the next person will fall into the same hole.

**Comment by mcgratta** [comment]
The wiki explains how to set the CRS for the elevation and landuse layers. But it doesn't say what to set for the OpenStreetMaps. There already is a setting, but I cannot see anything when I add the street map layer. So I must have changed something.

**Comment by emanuelegissi** [comment]
I tried to clarify the CRS explanations, for all layers. I hope now the wiki is better. Let me know if Africa is still overlapping the US (a sign of the times? ;-)

**Comment by mcgratta** [comment]
OK, thanks. Part of the problem for me is that QGIS seems to save many of my settings, and many of these are probably wrong. I need to figure out how to erase QGIS's memory and start fresh.

**Comment by emanuelegissi** [comment]
In QGIS go to menu Settings > User profiles > Open active profile folder

This is your current user profile. Delete it to start from scratch.

Is the wiki page ok?
Can I close this issue?

**Comment by mcgratta** [comment]
Yes, that's great. Thanks
