### ISSUE TITLE
qgis2fds stuck when exporting very large textures

### ISSUE THREAD

**Issue by emanuelegissi** [firetools/qgis2fds#13]

**Comment by rmcdermo** [comment]
I played with `Texture Layer resolution per meter` and confirm that a smaller value (.01) works fine and gets me over that step in the output and then the whole export procedure takes a reasonable amount of time.

The dialog is a bit tricky, though, as the default value is 1 and this is already quite high resolution.  But if you try to decrease the resolution, it just goes to 0.01 and this is the minimum.

So, first, when decreasing, the increment needs to be something other than 1.  And when coarsening beyond 1 pixel per meter, the increment needs to be smaller than 1.

Actually, it might make more sense for the parameter to be meters per pixel.

**Comment by rmcdermo** [comment]
Another option would be to play with what file size makes sense and loads in say 1-10 seconds (1-10 MB?). Then back calculate a rough resolution based on this size to use for the default.  I think we do not want this to cause a hang for new users.

**Comment by emanuelegissi** [comment]
Solved. Exporting a texture is much faster now, it's cancellable and there is a timeout.
In the meantime I discovered another bug on texture alignment for esoteric CRSs. Now it works, and it's very precise. But I need to refactor some code.

Please, test it.

**Comment by rmcdermo** [comment]
OK, will do.  Thanks!

**Comment by rmcdermo** [comment]
@emanuelegissi I have tested and confirm the new code is working well.  I also updated the wiki to reflect the slight changes in Export terrain parameters.
