### ISSUE TITLE
Exported .fds not running

### ISSUE THREAD

**Issue by jorgevaldivia91** [firetools/qgis2fds#23]
Emanuele, first of all, thank you for this amazing tool. I've been trying for several days to export an .fds file using `qgis2fds` with different DEM layers, places, etc (with and without fuel model layers). The only difference I've found so far is that im trying to do it from a place in South America. I followed the instructions in the quickstart section, and there is no problem in exporting the .fds file (no error in the qgis log while running qgis2fds). Nevertheless, it also exports a .bingeom file which I believe has the terrain data. But once I open the .fds file I get the following in the first line:
`! Generated by qgis2fds <__error__> on QGIS <3.14.1-Pi>`

I changed time to &TIME T_END=0. /, since I only need to see the geometry (terrain data) in smokeview. But once I do it, I get the following error in FDS.
```
ERROR: Problem with MISC line (CHID: terrain)
ERROR: FDS was improperly set-up - FDS stopped (CHID: terrain)
```

I tried searching more about that .bingeom file created with the qgis2fds tool, but found nothing (and in the quickstart there is no mention of that type of file). To be honest, I've been trying to export terrain data to fds for a long time (also trying BlenderFDS), but I just can't figure it out. In blender I make a mesh-cube-box around the DEM, open the DEM from blenderGIS and everything is ok, but then I need to set the mesh of the cube really small in order to see the data (I set the DEM data to voxels...), otherwise I see the terrain filled of cubes and holes within it in FDS. I'd really appreciate some help. Thanks in advance! (FYI, im running QGIS 3.14.1-pi on a Windows 10-64 bit machine / DEM resolution is 12.5 m -ALOS PALSAR- and I've also tried with SRTM / I'm using last Blender version with blenderFDS28x).

**Comment by mcgratta** [comment]
We are releasing a new version of FDS this week and this should solve this
problem. The FDS input file format has been evolving as QGIS2FDS has
evolved.

>

**Comment by jorgevaldivia91** [comment]
Oh I see, thank you Kevin :), have a nice weekend!

**Comment by emanuelegissi** [comment]
Thank you for your feedback.

What version of qgis2fds are you using? That from the QGIS channel or the
GitHub repo?

 I would be very interested in hearing your opinion on the wiki
documentation, too.

Emanuele

**Comment by jorgevaldivia91** [comment]
Emanuel, thank you for all you've done! 

Answering to your questions:
1) I downloaded qgis2fds from the GitHub repo (.zip file), and installed it in via qgis-pluggins. I also tried today removing the pluggin, download it again and re-installing it, but the result was the same.
2) I think the wiki is very good, however the only place where i've seen something related to generate terrain for FDS (via DEM) is in the examples shown here (the golden gate one).  There is not much information about it, but as far as I understand is a work in progress in FDS. 

I just wanted to thank you for all you've done. BlenderFDS and qgis2fds are amazing tools! Please keep doing it. I am a teaching assistant at the university and, together with the professor, we are proposing the students to run wildfire simulations of different places in South America using FDS, so we are trying to provide them the terrain data.

Have a nice weekend!
Sincerely, Jorge.

**Comment by emanuelegissi** [comment]
Thank you again.

You will find much more information on wildfire simulation in FDS user's
guide as soon as the next version is released.

I am pushing the qgis2fds plugin to the official QGIS repo as well, so your
students should be able to get it directly from QGIS, avoiding the
complexity of GitHub:
https://plugins.qgis.org/plugins/qgis2fds/

I am happy that you are using BlenderFDS as well. By the end of the summer,
I am quite sure I am going to release the new release for Blender 2.83.
Many improvements...

Have a great weekend,
Emanuele

**Comment by jorgevaldivia91** [comment]
Sounds amazing! I'll be waiting for both the updates and the wiki :) 
Thanks again Emanuel, you've contributed a lot to wildfire science-research. 
We are also trying to run some simulations via FlamMap and FDS of a wildfire that took place in Chile a couple of years ago, so we are planning to use qgis2fds for the terrain data. 
Have a nice week!
Jorge

**Comment by emanuelegissi** [comment]
If it is feasible, I would be more than happy to add your case to the
examples, with full acknowledgement.

Emanuele

**Comment by jorgevaldivia91** [comment]
It would be astounding! Once the results are published I'll definitely let you know and provide all the data/procedure. It will be just amazing to contribute in something.

**Comment by emanuelegissi** [comment]
Ok, thanks again. Looking forward to it.
Emanuele
