### ISSUE TITLE
Questions about ignition

### ISSUE THREAD

**Issue by dvswenson** [firetools/qgis2fds#25]
Two questions about ignition:

1. What does it mean to ignite the terrain? Does that mean that some vegetation is set to a burn state or does it mean that the ignition device is heating the vegetation until it ignites?

2. What is the best way to ignite the fire when working with geometry defined in bingeom created by QGIS2FDS? There are two issues: first is accessing the elevations of individual faces and the second is how to define the ignition.

In the FDS example fires (levelset2, level_set_fuel_model_1, etc) a VENT is used to ignite the fire, but I don't think I can use a vent on sloping terrain.
&SURF ID='SPOT IGN', VEG_LSET_IGNITE_TIME=0, COLOR='ORANGE', VEG_LSET_FUEL_INDEX=1 /
&VENT XB=475,525,475,525,0,0, SURF_ID='SPOT IGN' /

When using terrain, should I define a GEOM object using &GEOM?
&GEOM ID='terrain'
      SURF_ID='S1'
      IJK=ivals,jvals, XB=xmin,xmax,ymin,ymax,
      EXTEND_TERRAIN=etlog, ZVAL_HORIZON=zvhr,
      ZVALS=...

Thanks,
Dan Swenson

**Comment by mcgratta** [comment]
1. Depends on the mode. If you are just performing a level set calculation (mode=1), there is no ignition, but rather the fire front is just tracked through a quiescent environment. In cases where there is actually fire, ignition occurs at the time specified or when the front arrives. There is no "heating" to ignite the fuel.

2. On the VENT line, set GEOM=T and put the vent on the floor of the domain, literally the lowest value of z. The VENT will be projected upwards.

**Comment by dvswenson** [comment]
Thank you. That answers both questions.
