### ISSUE TITLE
Long qgis2fds processing time

### ISSUE THREAD

**Issue by mcgratta** [firetools/qgis2fds#28]
[Camp_Fire_LS_1.txt](https://github.com/firetools/qgis2fds/files/6205241/Camp_Fire_LS_1.txt)
Can you look at the attached qgis2fds log to see if I'm doing something wrong. I am trying to create a level set 1 input file for a patch of California that is approximately 46 km by 38 km, which I will cover with a mesh of 50 m. The process time was about 7 h. I assume that my DEM resolution is 30 m. Is this processing time normal?

**Comment by emanuelegissi** [comment]
According to your log file the domain size is 82414.21x78619.03 meters.

Are you working with online dem and landuse data? The servers are not very
happy with serving all that data...

So first make your data sources local, as explained in:
https://github.com/firetools/qgis2fds/wiki/Saving-remote-layers

And, by the way, I am improving the log readability.

Let me know if it works,
Ema

**Comment by mcgratta** [comment]
Are these coordinates in m?
```
&url=https://landfire.cr.usgs.gov/arcgis/services/Landfire/US_other/MapServer/WCSServer', 'dem_sampling' : 1, 'extent' : '-2166138.682700000,-2120163.249200000,2130253.100500000,2168581.135200000 [EPSG:5070]',
```

**Comment by emanuelegissi** [comment]
They should, as explained in:
https://epsg.io/5070-1252

**Comment by emanuelegissi** [comment]
Anyway, it depends on the CRS. The EPSG:5070 is metric, other CRSs are not.

I just pushed the new readable log system code to the qgis2fds repository.


Il giorno gio 25 mar 2021 alle ore 15:56 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
Great. Saving the layers locally sped up the process. It took only a few minutes. Thanks

**Comment by emanuelegissi** [comment]
Yeah! Great

Il giorno gio 25 mar 2021 alle ore 16:35 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
My fault, I forgot to bump the version number. I am doing it in 30 minutes


Il giorno gio 25 mar 2021 alle ore 17:32 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
I pushed the correction.

Il giorno gio 25 mar 2021 alle ore 17:38 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
[Camp_Fire_LS_1.txt](https://github.com/firetools/qgis2fds/files/6206651/Camp_Fire_LS_1.txt)
I am told that my terrain extent is larger than my DEM data, but I cannot understand why. I created local layers all with the same extent -- that of the mapping window.

**Comment by emanuelegissi** [comment]
Due to geographic transformations the resulting domain could become
slightly rotated.

In general, I download the dem data to be twice the size of the desired
domain, to be on the safe side.

Try to reduce your terrain extent or increase the size of downloaded dem
and landuse layers.

**Comment by mcgratta** [comment]
But I use my mouse to draw a rectangle. I assume that this is my FDS domain. I understand the rotation problem, but is there a way to be assured that where I carve out a rectangle is going to be my domain?

**Comment by emanuelegissi** [comment]
To be on the safe side, your domain is going to exactly contain the extent
you draw with your mouse.

Due to geographic transformation the domain can be rotated.

**Comment by emanuelegissi** [comment]
Yes, I'm going to add a wiki page on that.

**Comment by mcgratta** [comment]
I do not understand what you mean. Are you saying that currently when I draw a rectangle using the qgis2fds tool to describe my desired domain, that this is exactly what my domain is. Or is it that my domain is a rotated rectangle with the same size as my rectangle? Or a rotated rectangle inscribed (completely within) my specified rectangle?

**Comment by emanuelegissi** [comment]
This is why I want to add a wiki page, with a clear drawing of the
algorithm.

Your fds domain is going to be a slightly rotated rectangle escribed
(completely outside) of your specified rectangle.

So that you are not leaving out any of your areas of interest.

**Comment by emanuelegissi** [comment]
"Outscribed" perhaps?

**Comment by mcgratta** [comment]
Is it possible within QGIS to select a rectangle whose sides are parallel to lines of latitude and longitude? I assume that the FDS domain boundaries are parallel to latitude and longitude lines. Or can one rotate the map canvass 15° (or whatever) and then draw the rectangle? Is seems that the rotated fuel patches cause you much grief. Would it be better to work with DEM coordinates instead and interpolate the fuel patches?

**Comment by mcgratta** [comment]
I think the word should be "circumscribed" from the Latin "circum".

**Comment by emanuelegissi** [comment]
It's 8:00 p.m. here, sorry. I'm going to add a long explanation tomorrow.
We already discussed about this when speaking about the north bearing.
There is a reason why it's so complicated...

**Comment by mcgratta** [comment]
I understand. I just worry that the fuel patches might be causing you extra grief. Maybe the easiest thing to do now is just draw two rectangles. I have learned today how to manipulate these layers more easily. I think a compass image and rotated rectangle capture would be perfect, but I don't know if one is allowed to do that in QGIS -- the rotated rectangle, I mean.

**Comment by emanuelegissi** [comment]
This morning I have been working on refactoring the projection code, before
writing the wiki page.
It is not ready yet. I will keep you posted.

Il giorno gio 25 mar 2021 alle ore 20:14 Kevin McGrattan <
***@***.***> ha scritto:
