### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by asbova17** [firetools/qgis2fds#29]
Hello- Thanks for this tool! Unfortunately, I'm having a repeated issue when I run the script. I've set up the domain and layers as described in the wiki. This is the traceback:

Traceback (most recent call last):
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/qgis2fds_algorithm.py", line 688, in processAlgorithm
utm_origin=utm_origin,
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/geometry.py", line 35, in get_geometry
verts = _get_verts(feedback=feedback, m=matrix)
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/geometry.py", line 181, in _get_verts
dx, dy = m[0, 1] - m[0, 0], m[1, 0] - m[0, 0] # displacements
IndexError: index 1 is out of bounds for axis 1 with size 1

Have you seen this error before?

**Comment by emanuelegissi** [comment]
Never seen that before.
Can you send me the full log, the qgis file, and all the data files?

**Comment by asbova17** [comment]
Hi Emanuele,

The qgis project file and a perimeter shape file (for reference) are attached.  Other than that I'm using the US_200F13_19 and US_DEM2016 layers from WCS. Thanks for your help! The log is below:

QGIS version: 3.16.3-Hannover
QGIS code revision: 3a90ea3afd
Qt version: 5.14.2
GDAL version: 3.1.2
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Export terrain' starting…
Input parameters:
{ 'chid' : 'ElPortal_Qgis2fds_terrain_no_fire', 'dem_layer' : 'dpiMode=7&identifier=US_DEM2016&url=https://landfire.cr.usgs.gov/arcgis/services/Landfire/US_other/MapServer/WCSServer', 'dem_sampling' : 2, 'extent' : '-119.810726085,-119.747503772,37.677835123,37.745600356 [EPSG:4326]', 'fire_origin' : None, 'landuse_layer' : 'dpiMode=7&identifier=US_200F13_19&url=https://landfire.cr.usgs.gov/arcgis/services/Landfire/US_200/MapServer/WCSServer', 'landuse_type' : 0, 'origin' : None, 'path' : '/Volumes/Accelsior 4M2/FDS_Simulations/El_Portal', 'sampling_layer' : 'TEMPORARY_OUTPUT', 'tex_layer' : 'crs=EPSG:3857&format&type=xyz&url=https://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=19&zmin=0', 'tex_pixel_size' : 30 }

Domain origin: -119.779115, 37.711718 (WGS 84)
Fire origin: -119.779115, 37.711718 (WGS 84)

Project CRS: <WGS 84>
DEM layer CRS: <NAD83 / Conus Albers>
Landuse layer CRS: <NAD83 / Conus Albers>
Texture layer CRS: <WGS 84 / Pseudo-Mercator>
FDS CRS: <WGS 84 / UTM zone 11N>

FDS domain (MESH)
size: 5797.4 x 7686.1 meters

DEM layer sampling for FDS terrain (GEOM)
resolution: 60.0 x 60.0 meters
geometry: 18750 verts, 36952 faces

Press <Cancel> to interrupt the execution.

(1/7) Creating sampling grid from DEM layer...
Results: {'OUTPUT': 'Grid_65f8160d_619c_47d1_88df_c10ac2717c68'}

(2/7) Rendering, cropping, and writing texture image, timeout in 30s...
Texture size: 308 x 339 pixels, 9240.2 x 10180.4 meters
Saved (in 0.04 s): </Volumes/Accelsior 4M2/FDS_Simulations/El_Portal/ElPortal_Qgis2fds_terrain_no_fire_tex.png>

(3/7) Draping elevations from DEM layer to sampling grid...
Results: {'OUTPUT': 'Draped_a8b062c2_3482_4553_8336_b0ac46e7fdf8'}

(4/7) Reprojecting sampling grid layer to UTM CRS...
Results: {'OUTPUT': 'Reprojected_f7983118_f615_437b_8f7f_d03ae18f4857'}

(5/7) Sampling landuse layer...
Results: {'OUTPUT': 'Sampled_612d3c0e_2e65_4605_aa58_77cd345dbb6b'}

(6/7) Building FDS geometry...
Point matrix...
Faces and landuses...
Verts...
Traceback (most recent call last):
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/qgis2fds_algorithm.py", line 688, in processAlgorithm
utm_origin=utm_origin,
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/geometry.py", line 35, in get_geometry
verts = _get_verts(feedback=feedback, m=matrix)
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/geometry.py", line 181, in _get_verts
dx, dy = m[0, 1] - m[0, 0], m[1, 0] - m[0, 0] # displacements
IndexError: index 1 is out of bounds for axis 1 with size 1

Execution failed after 2.56 seconds
[Historic_Perimeters_Combined_2000-2018.zip](https://github.com/firetools/qgis2fds/files/6290406/Historic_Perimeters_Combined_2000-2018.zip)
[ElPortalFire_Terrain.qgz.zip](https://github.com/firetools/qgis2fds/files/6290407/ElPortalFire_Terrain.qgz.zip)

**Comment by emanuelegissi** [comment]
Well, it works, here. I cannot reproduce your bug.
I am opening it with QGIS 3.18 on Fedora Linux.
I attach the qgis updated file, to be used with your data.
Let me know.
Emanuele

[image: image.png]
[image: image.png]

Il giorno sab 10 apr 2021 alle ore 19:36 asbova17 ***@***.***>
ha scritto:

**Comment by asbova17** [comment]
Hi Emanuele- I may be missing something. I didn't see an attached qgis file. Thanks, Tony

**Comment by emanuelegissi** [comment]
Here it is, sorry:
[ElPortalFire_Terrain_01.qgz.txt](https://github.com/firetools/qgis2fds/files/6301881/ElPortalFire_Terrain_01.qgz.txt)

**Comment by asbova17** [comment]
Thanks! Unfortunately it still doesn't work for me. The coordinate matrix is being returned from the _get_matrix function in geometry.py with only a single row. 
The x-y coordinates in the point_layer returned at line 668 in qgis2fds_algorithm.py (which will be passed as 'layer' in the geometry functions) are all at the lowest and highest numbers (x=1.2e-322, y= 9.087003706793628e+223). That's as far as I've been able to go so far.

**Comment by emanuelegissi** [comment]
I would try to reinstall qgis from scratch to the latest version 3.18 (it
seems to me that you are using 3.16).

Please, remove your local settings as well before installing.
Maybe it's due to a broken installation.

And try to rebuild from scratch your current case, it should not take too
much time.

If even this is not working, I propose a video call to talk and take a
direct look at what's going on.

Emanuele

**Comment by asbova17** [comment]
I should have mentioned that I did install 3.18 and redo the case before I sent the last message. I didn't remove my local settings first, though, so maybe that's the problem. I'll try that and reinstall but will have to make sure it doesn't affect my other projects. I'll let you know. Cheers, Tony

**Comment by emanuelegissi** [comment]
Ok Tony

**Comment by asbova17** [comment]
Hi Emanuele- I was able to return to this recently and am still having the same issue. A colleague installed qgis on his system (a Mac desktop - same as mine) for the first time and had the same error, so I'm wondering if this could be an issue with qgis on a mac.  

If I save the sampling grid to a file (.gpkg), instead of to a temporary layer, the grid is saved correctly but the the following error is produced: 

(6/7) Building FDS geometry...
Traceback (most recent call last):
File "/Users/anthonybova/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2fds/qgis2fds_algorithm.py", line 685, in processAlgorithm
feedback.pushInfo(f"Feature count: {point_layer.featureCount()}")
AttributeError: 'NoneType' object has no attribute 'featureCount'

Execution failed after 3.05 seconds

Loading resulting layers
Algorithm 'Export terrain' finished

(All of the previous steps are completed as before). The grid file that is output looks correct when I load it into qgis.
Any help is appreciated.

**Comment by emanuelegissi** [comment]
Let's organize a video call. Please, contact me by email:
***@***.***

Il giorno lun 3 mag 2021 alle ore 16:52 asbova17 ***@***.***>
ha scritto:

**Comment by rmcdermo** [comment]
For what it's worth, Emanuele's input file work for me with QGIS3.14, but failed with QGIS3.20.  I get the following error message in the log:
```
(6/7) Building FDS geometry...
Point matrix...
Faces and landuses...
[QGIS bug] Too small point matrix, cannot proceed with face building: 72570x1
Execution failed after 8.08 seconds
```
Note this is a fresh install of QGIS3.20 and fresh clone of the qgis2fds repo.

**Comment by emanuelegissi** [comment]
Thanks for trying out. So this a qgis regression on the MacOS version...
Please, please keep using 3.14 until I figure out a way to debug it.
The main problem is that I have to find a Mac computer.

**Comment by rmcdermo** [comment]
It might be painful, but we could do a screen share and debug from my end.

**Comment by emanuelegissi** [comment]
Even asynchronous would be great:
I push some debug code in the repo and you send the log back to me. Let's
discuss it next week, ok?

**Comment by rmcdermo** [comment]
Sounds good.  This is a case where you could create a debug branch.  I am using a cloned version of code, so I can update any branch changes in real time.

**Comment by emanuelegissi** [comment]
Current master branch should fix the issue.
After double checks, a new release very soon!

**Comment by rmcdermo** [comment]
Works for me with QGIS3.20 and latest source for qgis2fds.  Thanks!

**Comment by emanuelegissi** [comment]
Ok, thank you
