### ISSUE TITLE
ERROR: GEOM ID

### ISSUE THREAD

**Issue by Marco-a21** [firetools/qgis2fds#30]
I'm trying to use "qgis2fds" from a tile of Open Street Map but I get the following error:

ERROR: GEOM ID=Terrain. Check &GEOM input line. (CHID: golden_gate)

ERROR: FDS was improperly set-up - FDS stopped (CHID: golden_gate)

even though I installed the nightly version of FDS.

I ran the "quickstart" case and attached are: the project file, the layers data and the log file
Thanks in advance

[quickstart.zip](https://github.com/firetools/qgis2fds/files/6345842/quickstart.zip)

**Comment by mcgratta** [comment]
I will try your case.

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/115572482-ee7a1a00-a28d-11eb-8e94-b3eb2c608daa.png)
I opened `quickstart.qgz` in QGIS 3.18.1-Zurich and created an FDS input file using qgis2fds that I obtained from the firetools/qgis2fds GitHub site. I then ran this case using the latest FDS source code. The resulting Smokeview image is shown above. Are you able to do this? Or are you talking about another case that you have created?

**Comment by mcgratta** [comment]
[golden_gate.txt](https://github.com/firetools/qgis2fds/files/6351866/golden_gate.txt)
Here is the FDS input file that was created by qgis2fds, version 0.56. I changed the suffix to .txt so that I could post the file here. Is your FDS input file the same as this one?

**Comment by mcgratta** [comment]
OK, my guess is that this is either a problem of computer memory or file line endings. I ran QGIS on my Windows laptop, but then ran the FDS case on my linux cluster, using only a single process. Are you running the case under Windows or linux?

**Comment by Marco-a21** [comment]
Windows
My workstation has 64 Gb of RAM.
Do you think is it worth trying on a linux machine?

Marco

Il giorno mer 21 apr 2021 alle ore 17:36 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
No. I just ran the case on my Windows laptop. My only suggestion is to combine all the parameters of the GEOM record onto a single line, ending with the /. I wonder if this is some strange line ending problem.

**Comment by Marco-a21** [comment]
I think the problem is in:

BINARY_FILE='golden_gate_terrain.bingeom'

If I remove it from the namelist &GEOM, I'm able to complete the set-up.

Marco

Il giorno mer 21 apr 2021 alle ore 18:30 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
Yes, but this file contains the geometry (terrain) information. If you
remove it, you remove the terrain. Is this file included in your working
directory? qgis2fds produces it.

>

**Comment by Marco-a21** [comment]
Yes, the file *.bingeom is included.
I was wondering if that piece of information could be helpful to find out
the reason for the malfunctioning.
I tried to put the whole namelist &GEOM on a single line but it didn't work.

However, I discovered that the png file (e.g. golden_gate_tex.png) is not
generated by qgis2fds.

Marco

Il giorno gio 22 apr 2021 alle ore 14:24 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
The png file is only a texture.
The case should work even without it.

**Comment by mcgratta** [comment]
Somehow your file has become corrupted. What happens if you completely retype the GEOM line?

Ema -- can you run the case that I attached? It runs for me both under linux and Windows. It is the file that qgis2fds creates and I did not have to modify it.

**Comment by emanuelegissi** [comment]
I will take a look today and let you know

**Comment by emanuelegissi** [comment]
The files run ok here.

@Marco may you send me the qgis2fds output (bingeom, texture, and fds file)?
I would like to check byte by byte if your bingeom binary file is exactly
the same as mine.

If they are not identical, it is a qgis2fds issue. Otherwise I don't know...

Il giorno ven 23 apr 2021 alle ore 07:38 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
Ema -- I generated the fds, texture, and bingeom directly from the qgz file that Marco posted. I did not try to run Marco's fds file directly. I would do a byte count. I wonder if it is a line ending issue.

**Comment by emanuelegissi** [comment]
@Kevin: I was wondering if it is Marco's qgis2fds installation producing an
incorrect bingeom. This is why I was asking his bingeom to compare it byte
to byte to mine, that works here.


Il giorno ven 23 apr 2021 alle ore 21:55 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
OK, but it appears that the problem is that FDS cannot read his GEOM
parameters. This is why I suggested that he rewrite the GEOM parameters or
combine the terms onto one single line.

>

**Comment by emanuelegissi** [comment]
Ok ok, I was just thinking about checking his bingeom as a further step.

**Comment by Marco-a21** [comment]
Hi Guys,

Thank you very much for your efforts about my issues and my sincere
apologies for this late reply.
As suggested by Kevin, I wrote ex-novo the namelist GEOM on a single line
but I didn't get either any positive
result or hunches to solve the problems, apart the indication (maybe
obvious) that the responsible seems to be
the command BINARY_FILE='golden_gate_terrain.bingeom'.
In attachment the files required by Emanuele (just bingeom and fds files.
The texture one is not generated).

Thank you again for your time (in the meanwhile I'm trying to reinstall
everything on my own private pc).

Best regards,

Marco

Il giorno ven 23 apr 2021 alle ore 22:28 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
I'm afraid your file did not pass. Please change the extension to txt

**Comment by Marco-a21** [comment]
Ok.

In attachment the new folder.

Marco


Il giorno mar 27 apr 2021 alle ore 10:57 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
It didn't work again. Try as a zip file or share a link, please

**Comment by Marco-a21** [comment]
OK, let's try with a link (the FDS file has still the txt extension):

http://webftp.enginsoft.it/mesagne/FDS/golden_gate2.zip

Thank you,

Marco

Il giorno mar 27 apr 2021 alle ore 15:22 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
Well, the problem now is that the link is ok but I cannot reach the file.
What about a Google Drive share?

Il giorno mar 27 apr 2021 alle ore 15:48 Marco-a21 ***@***.***>
ha scritto:

**Comment by mcgratta** [comment]
I was able to download `golden_gate2.zip` and run the enclosed fds file successfully.

**Comment by emanuelegissi** [comment]
Marco, it seems we cannot reproduce your bug...
Please, double check you have the latest FDS nightly installed.

**Comment by Marco-a21** [comment]
OK, thank you for your effort.
I'll let you know.

Best regards,

Marco

Il giorno ven 30 apr 2021 alle ore 16:02 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
Please, try the newest release
