### ISSUE TITLE
WCS connections not appearing

### ISSUE THREAD

**Issue by k3iki** [firetools/qgis2fds#46]
Landfire WCS connections not appearing in QGIS 3.26. Re-entries get the prompt "Should the exising connection to Landfire CONUS LF be overwritten?"
![Screenshot 2023-04-21 at 11 04 25 AM](https://user-images.githubusercontent.com/116380980/233706272-1ef8052d-2635-4a33-9274-d241eebf2961.png)
![Screenshot 2023-04-21 at 11 05 17 AM](https://user-images.githubusercontent.com/116380980/233706278-1088da62-c4e5-44ac-a745-ed6ea2238ca6.png)
![Screenshot 2023-04-21 at 11 05 36 AM](https://user-images.githubusercontent.com/116380980/233706280-99ac5a97-63d5-48d2-8480-f507c877ebd5.png)
![Screenshot 2023-04-21 at 11 05 43 AM](https://user-images.githubusercontent.com/116380980/233706282-c96c603a-702d-49c9-8bd3-2035465505cc.png)

**Comment by rmcdermo** [comment]
Thanks for the report.  We will look at it.

**Comment by rmcdermo** [comment]
Can you please try with the latest QGIS?  It is working for me with version 3.30.1-'s-Hertogenbosch.

Note: I added one small change to the [Quickstart](https://github.com/firetools/qgis2fds/wiki/Quickstart) wiki, which is that you need to click `Connect` after typing in the URLs for the databases in Step 1.

Here is the result I get.

![Screenshot 2023-05-30 at 3 25 51 PM](https://github.com/firetools/qgis2fds/assets/4418497/507238ab-9f30-4b2c-9497-27d7a63f4149)

**Comment by rmcdermo** [comment]
Great.  Sorry it took so long for me to look at this.
