### ISSUE TITLE
dialog disappears behind qgis layer panel after input of auxiliary files

### ISSUE THREAD

**Issue by rmcdermo** [firetools/qgis2fds#51]
@emanuelegissi I've been playing with setting up a new case and with the latest qgis2fds I keep running into the situation where the `Export Terrain` dialog disappears behind the main qgis layer panel after I enter a wind file, for example.  It also happened to me when entering the landuse_type file.  It took me a long time to realize what was going on and I kept restarting the case.  Below, you see roughly what is happening.  Can we try to make sure the `Export Terrain` dialog stays in the foreground?  Thanks!

<img width="2560" alt="Screenshot 2023-06-21 at 3 29 38 PM" src="https://github.com/firetools/qgis2fds/assets/4418497/3f00d01f-1bf7-4161-b8ae-fa4444f86fd6">

**Comment by rmcdermo** [comment]
Well, seems this is the same as point 3 in Issue #50 .  Feel free to close if you want.

**Comment by rmcdermo** [comment]
I just discovered something else about this behavior... apparently, these Export Terrain windows do not close unless you explicitly close them... they just pile up on top of one another.  It seems to me that we do not want more than one Export Terrain dialog window open at a time.  So, we should probably close any that are open if we click on Export Terrain again.

**Comment by emanuelegissi** [comment]
I am sorry, cannot fix. This is a QGIS UI behaviour.
