### ISSUE TITLE
Qgis2fds Verification

### ISSUE THREAD

**Issue by johodges** [firetools/qgis2fds#55]
I have been working through the qgis2fds verification with the updates discussed in https://github.com/firetools/qgis2fds/pull/53. Unfortunately, the current master qgis2fds and master qgisfds.verification repositories do not reproduce the reference inputs for each case. I have attached a few slides comparing the current reference files included in the repo, the files generated using the two master branches, and the files generated using https://github.com/firetools/qgis2fds/pull/53 and https://github.com/firetools/qgisfds.verification/pull/1. It looks to me like the files generated with the linked PRs are similar enough to the versions of the files in the repo. The differences in DEM look primarily due to different layer maps and resolution used in generating the verification cases. However, these do not align between the current reference files and the current master branch either. Happy to discuss if needed, just let me know.

[qgis2fds_verification.pptx](https://github.com/firetools/qgis2fds/files/12006281/qgis2fds_verification.pptx)

**Comment by rmcdermo** [comment]
Thanks, Jonathan.  I am working through trying to make a small case with your latest repo to see if the bingeom generated by qgis2fds aligned with the FDS mesh in Smokeview.  I'm being plagued by the DEM server timing out on me...

Perhaps tomorrow, if you have time, we can try to assess the state of things.  Thanks
