### ISSUE TITLE
Mesh alignment issue

### ISSUE THREAD

**Issue by johodges** [firetools/qgis2fds#57]
Master has a minor mesh alignment issue. The mesh XB used in calculation of DX and DY for MULT is not rounded in that calculation but is rounded when exported to an FDS file. This sometimes leads to a misalignment of the mesh. See the local case in the attached example. Fixed in https://github.com/johodges/qgis2fds/tree/develop in 36113cb301ded57d2105ced407ece32c0f619a3e
[Las_Conchas_Fire.zip](https://github.com/firetools/qgis2fds/files/12069612/Las_Conchas_Fire.zip)

**Comment by rmcdermo** [comment]
@johodges Thanks.  Sorry, I was out yesterday.  I will review today.

**Comment by rmcdermo** [comment]
@johodges do you have a branch that just fixes the mesh issue?  If so, I can test and we are merge that to master.

Kevin and I talked and we need to get qgis2fds functional before the next FDS release can take place.  Thanks

**Comment by rmcdermo** [comment]
So, is this ready for PR?  As we discussed, we should work in atomic changes.  Fixing that mesh boundary issue is a good fix that we could merge to the main branch asap.

**Comment by johodges** [comment]
Unfortunately my develop branch has the other changes that we wanted to break up into multiple PRs. I will set up my master_rebase branch with the minimum changes to get a PR in for Ema to review when he is back next week.

**Comment by johodges** [comment]
Fixed in dev branch in f2ef0c0.
